title: Aurora Framework
email: auroraframework@gmail.com
description: A Powerful General Purpose Framework
google_analytics:
show_downloads: false
github_username: aurorafw

theme: jekyll-theme-minimal
markdown: kramdown

plugins:
  - jekyll-mentions

exclude: [vendor, "Gemfile", "Gemfile.lock"]